dependencies = []
description = "LinK is a networking agent that will let multiple hosts share a virtual IP."
destination_server = ["app-hosting-node", "database-hosting-node", "internal"]
flags = ["cli", "deployed-by-chef", "tools"]
languages = ["go", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.0"
