// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/locker (interfaces: EtcdLeaseManager)

// Package locker is a generated GoMock package.
package locker

import (
	context "context"
	reflect "reflect"

	v3 "go.etcd.io/etcd/client/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockEtcdLeaseManager is a mock of EtcdLeaseManager interface.
type MockEtcdLeaseManager struct {
	ctrl     *gomock.Controller
	recorder *MockEtcdLeaseManagerMockRecorder
	isgomock struct{}
}

// MockEtcdLeaseManagerMockRecorder is the mock recorder for MockEtcdLeaseManager.
type MockEtcdLeaseManagerMockRecorder struct {
	mock *MockEtcdLeaseManager
}

// NewMockEtcdLeaseManager creates a new mock instance.
func NewMockEtcdLeaseManager(ctrl *gomock.Controller) *MockEtcdLeaseManager {
	mock := &MockEtcdLeaseManager{ctrl: ctrl}
	mock.recorder = &MockEtcdLeaseManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtcdLeaseManager) EXPECT() *MockEtcdLeaseManagerMockRecorder {
	return m.recorder
}

// GetLease mocks base method.
func (m *MockEtcdLeaseManager) GetLease(ctx context.Context) (v3.LeaseID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLease", ctx)
	ret0, _ := ret[0].(v3.LeaseID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLease indicates an expected call of GetLease.
func (mr *MockEtcdLeaseManagerMockRecorder) GetLease(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLease", reflect.TypeOf((*MockEtcdLeaseManager)(nil).GetLease), ctx)
}

// MarkLeaseAsDirty mocks base method.
func (m *MockEtcdLeaseManager) MarkLeaseAsDirty(ctx context.Context, leaseID v3.LeaseID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkLeaseAsDirty", ctx, leaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkLeaseAsDirty indicates an expected call of MarkLeaseAsDirty.
func (mr *MockEtcdLeaseManagerMockRecorder) MarkLeaseAsDirty(ctx, leaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkLeaseAsDirty", reflect.TypeOf((*MockEtcdLeaseManager)(nil).MarkLeaseAsDirty), ctx, leaseID)
}

// Start mocks base method.
func (m *MockEtcdLeaseManager) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEtcdLeaseManagerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEtcdLeaseManager)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockEtcdLeaseManager) Stop(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", ctx)
}

// Stop indicates an expected call of Stop.
func (mr *MockEtcdLeaseManagerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEtcdLeaseManager)(nil).Stop), ctx)
}

// SubscribeToLeaseChange mocks base method.
func (m *MockEtcdLeaseManager) SubscribeToLeaseChange(ctx context.Context, callback LeaseChangedCallback) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToLeaseChange", ctx, callback)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToLeaseChange indicates an expected call of SubscribeToLeaseChange.
func (mr *MockEtcdLeaseManagerMockRecorder) SubscribeToLeaseChange(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToLeaseChange", reflect.TypeOf((*MockEtcdLeaseManager)(nil).SubscribeToLeaseChange), ctx, callback)
}

// UnsubscribeToLeaseChange mocks base method.
func (m *MockEtcdLeaseManager) UnsubscribeToLeaseChange(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeToLeaseChange", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeToLeaseChange indicates an expected call of UnsubscribeToLeaseChange.
func (mr *MockEtcdLeaseManagerMockRecorder) UnsubscribeToLeaseChange(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeToLeaseChange", reflect.TypeOf((*MockEtcdLeaseManager)(nil).UnsubscribeToLeaseChange), ctx, id)
}
