// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/scheduler (interfaces: Scheduler)

// Package schedulermock is a generated GoMock package.
package schedulermock

import (
	context "context"
	reflect "reflect"

	models "github.com/Scalingo/link/v3/models"
	scheduler "github.com/Scalingo/link/v3/scheduler"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// ConfiguredEndpoints mocks base method.
func (m *MockScheduler) ConfiguredEndpoints(ctx context.Context) scheduler.EndpointsWithStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfiguredEndpoints", ctx)
	ret0, _ := ret[0].(scheduler.EndpointsWithStatus)
	return ret0
}

// ConfiguredEndpoints indicates an expected call of ConfiguredEndpoints.
func (mr *MockSchedulerMockRecorder) ConfiguredEndpoints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfiguredEndpoints", reflect.TypeOf((*MockScheduler)(nil).ConfiguredEndpoints), ctx)
}

// EndpointCount mocks base method.
func (m *MockScheduler) EndpointCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// EndpointCount indicates an expected call of EndpointCount.
func (mr *MockSchedulerMockRecorder) EndpointCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointCount", reflect.TypeOf((*MockScheduler)(nil).EndpointCount))
}

// Failover mocks base method.
func (m *MockScheduler) Failover(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Failover", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Failover indicates an expected call of Failover.
func (mr *MockSchedulerMockRecorder) Failover(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Failover", reflect.TypeOf((*MockScheduler)(nil).Failover), ctx, id)
}

// GetEndpoint mocks base method.
func (m *MockScheduler) GetEndpoint(ctx context.Context, id string) *scheduler.EndpointWithStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndpoint", ctx, id)
	ret0, _ := ret[0].(*scheduler.EndpointWithStatus)
	return ret0
}

// GetEndpoint indicates an expected call of GetEndpoint.
func (mr *MockSchedulerMockRecorder) GetEndpoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndpoint", reflect.TypeOf((*MockScheduler)(nil).GetEndpoint), ctx, id)
}

// Start mocks base method.
func (m *MockScheduler) Start(ctx context.Context, endpoint models.Endpoint) (models.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, endpoint)
	ret0, _ := ret[0].(models.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSchedulerMockRecorder) Start(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockScheduler)(nil).Start), ctx, endpoint)
}

// Status mocks base method.
func (m *MockScheduler) Status(id string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockSchedulerMockRecorder) Status(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockScheduler)(nil).Status), id)
}

// Stop mocks base method.
func (m *MockScheduler) Stop(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSchedulerMockRecorder) Stop(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockScheduler)(nil).Stop), ctx, id)
}

// UpdateEndpoint mocks base method.
func (m *MockScheduler) UpdateEndpoint(ctx context.Context, endpoint models.Endpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEndpoint", ctx, endpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEndpoint indicates an expected call of UpdateEndpoint.
func (mr *MockSchedulerMockRecorder) UpdateEndpoint(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpoint", reflect.TypeOf((*MockScheduler)(nil).UpdateEndpoint), ctx, endpoint)
}
