// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/endpoint (interfaces: Creator)

// Package endpointmock is a generated GoMock package.
package endpointmock

import (
	context "context"
	reflect "reflect"

	endpoint "github.com/Scalingo/link/v3/endpoint"
	models "github.com/Scalingo/link/v3/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCreator is a mock of Creator interface.
type MockCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCreatorMockRecorder
	isgomock struct{}
}

// MockCreatorMockRecorder is the mock recorder for MockCreator.
type MockCreatorMockRecorder struct {
	mock *MockCreator
}

// NewMockCreator creates a new mock instance.
func NewMockCreator(ctrl *gomock.Controller) *MockCreator {
	mock := &MockCreator{ctrl: ctrl}
	mock.recorder = &MockCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreator) EXPECT() *MockCreatorMockRecorder {
	return m.recorder
}

// CreateEndpoint mocks base method.
func (m *MockCreator) CreateEndpoint(ctx context.Context, params endpoint.CreateEndpointParams) (models.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEndpoint", ctx, params)
	ret0, _ := ret[0].(models.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEndpoint indicates an expected call of CreateEndpoint.
func (mr *MockCreatorMockRecorder) CreateEndpoint(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEndpoint", reflect.TypeOf((*MockCreator)(nil).CreateEndpoint), ctx, params)
}
