// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/api (interfaces: Client)

// Package apimock is a generated GoMock package.
package apimock

import (
	context "context"
	reflect "reflect"

	api "github.com/Scalingo/link/v3/api"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddEndpoint mocks base method.
func (m *MockClient) AddEndpoint(ctx context.Context, params api.AddEndpointParams) (api.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEndpoint", ctx, params)
	ret0, _ := ret[0].(api.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddEndpoint indicates an expected call of AddEndpoint.
func (mr *MockClientMockRecorder) AddEndpoint(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEndpoint", reflect.TypeOf((*MockClient)(nil).AddEndpoint), ctx, params)
}

// Failover mocks base method.
func (m *MockClient) Failover(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Failover", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Failover indicates an expected call of Failover.
func (mr *MockClientMockRecorder) Failover(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Failover", reflect.TypeOf((*MockClient)(nil).Failover), ctx, id)
}

// GetEndpoint mocks base method.
func (m *MockClient) GetEndpoint(ctx context.Context, id string) (api.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndpoint", ctx, id)
	ret0, _ := ret[0].(api.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEndpoint indicates an expected call of GetEndpoint.
func (mr *MockClientMockRecorder) GetEndpoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndpoint", reflect.TypeOf((*MockClient)(nil).GetEndpoint), ctx, id)
}

// GetEndpointHosts mocks base method.
func (m *MockClient) GetEndpointHosts(ctx context.Context, id string) ([]api.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndpointHosts", ctx, id)
	ret0, _ := ret[0].([]api.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEndpointHosts indicates an expected call of GetEndpointHosts.
func (mr *MockClientMockRecorder) GetEndpointHosts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndpointHosts", reflect.TypeOf((*MockClient)(nil).GetEndpointHosts), ctx, id)
}

// ListEndpoints mocks base method.
func (m *MockClient) ListEndpoints(ctx context.Context) ([]api.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEndpoints", ctx)
	ret0, _ := ret[0].([]api.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEndpoints indicates an expected call of ListEndpoints.
func (mr *MockClientMockRecorder) ListEndpoints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEndpoints", reflect.TypeOf((*MockClient)(nil).ListEndpoints), ctx)
}

// RemoveEndpoint mocks base method.
func (m *MockClient) RemoveEndpoint(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEndpoint", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEndpoint indicates an expected call of RemoveEndpoint.
func (mr *MockClientMockRecorder) RemoveEndpoint(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEndpoint", reflect.TypeOf((*MockClient)(nil).RemoveEndpoint), ctx, id)
}

// RotateEncryptionKey mocks base method.
func (m *MockClient) RotateEncryptionKey(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateEncryptionKey", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateEncryptionKey indicates an expected call of RotateEncryptionKey.
func (mr *MockClientMockRecorder) RotateEncryptionKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateEncryptionKey", reflect.TypeOf((*MockClient)(nil).RotateEncryptionKey), ctx)
}

// UpdateEndpoint mocks base method.
func (m *MockClient) UpdateEndpoint(ctx context.Context, id string, params api.UpdateEndpointParams) (api.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEndpoint", ctx, id, params)
	ret0, _ := ret[0].(api.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEndpoint indicates an expected call of UpdateEndpoint.
func (mr *MockClientMockRecorder) UpdateEndpoint(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpoint", reflect.TypeOf((*MockClient)(nil).UpdateEndpoint), ctx, id, params)
}

// Version mocks base method.
func (m *MockClient) Version(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockClientMockRecorder) Version(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockClient)(nil).Version), ctx)
}
