// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/plugin (interfaces: Plugin)

// Package pluginmock is a generated GoMock package.
package pluginmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockPlugin) Activate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockPluginMockRecorder) Activate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockPlugin)(nil).Activate), ctx)
}

// Deactivate mocks base method.
func (m *MockPlugin) Deactivate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockPluginMockRecorder) Deactivate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockPlugin)(nil).Deactivate), ctx)
}

// ElectionKey mocks base method.
func (m *MockPlugin) ElectionKey(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ElectionKey", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// ElectionKey indicates an expected call of ElectionKey.
func (mr *MockPluginMockRecorder) ElectionKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ElectionKey", reflect.TypeOf((*MockPlugin)(nil).ElectionKey), ctx)
}

// Ensure mocks base method.
func (m *MockPlugin) Ensure(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure.
func (mr *MockPluginMockRecorder) Ensure(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockPlugin)(nil).Ensure), ctx)
}
