// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/link/v3/models (interfaces: EncryptedStorage)

// Package models is a generated GoMock package.
package models

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptedStorage is a mock of EncryptedStorage interface.
type MockEncryptedStorage struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptedStorageMockRecorder
	isgomock struct{}
}

// MockEncryptedStorageMockRecorder is the mock recorder for MockEncryptedStorage.
type MockEncryptedStorageMockRecorder struct {
	mock *MockEncryptedStorage
}

// NewMockEncryptedStorage creates a new mock instance.
func NewMockEncryptedStorage(ctrl *gomock.Controller) *MockEncryptedStorage {
	mock := &MockEncryptedStorage{ctrl: ctrl}
	mock.recorder = &MockEncryptedStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptedStorage) EXPECT() *MockEncryptedStorageMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockEncryptedStorage) Cleanup(ctx context.Context, endpointID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, endpointID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockEncryptedStorageMockRecorder) Cleanup(ctx, endpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockEncryptedStorage)(nil).Cleanup), ctx, endpointID)
}

// Decrypt mocks base method.
func (m *MockEncryptedStorage) Decrypt(ctx context.Context, data EncryptedDataLink, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptedStorageMockRecorder) Decrypt(ctx, data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptedStorage)(nil).Decrypt), ctx, data, v)
}

// Encrypt mocks base method.
func (m *MockEncryptedStorage) Encrypt(ctx context.Context, endpointID string, data any) (EncryptedDataLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, endpointID, data)
	ret0, _ := ret[0].(EncryptedDataLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptedStorageMockRecorder) Encrypt(ctx, endpointID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptedStorage)(nil).Encrypt), ctx, endpointID, data)
}

// RotateEncryptionKey mocks base method.
func (m *MockEncryptedStorage) RotateEncryptionKey(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateEncryptionKey", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateEncryptionKey indicates an expected call of RotateEncryptionKey.
func (mr *MockEncryptedStorageMockRecorder) RotateEncryptionKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateEncryptionKey", reflect.TypeOf((*MockEncryptedStorage)(nil).RotateEncryptionKey), ctx)
}
